# Generated by Django 5.0 on 2023-12-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_First_Name', models.CharField(max_length=10)),
                ('Emp_Last_Name', models.CharField(max_length=10)),
                ('Emp_Designation', models.CharField(max_length=20)),
                ('Emp_Salary', models.IntegerField()),
                ('Emp_Company', models.CharField(max_length=20)),
            ],
        ),
    ]
